name: Test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: python .github/check_examples.py
    - run: npm ci
    - run: npm run build-tsc
    - run: npm test
    - run: npm run check